# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-22 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=32)),
                ('g_age', models.IntegerField(default=18)),
                ('g_sex', models.NullBooleanField(default=False)),
                ('g_vip', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=32)),
                ('g_price', models.IntegerField(default=0)),
                ('g_desc', models.TextField()),
                ('g_is_public_testing', models.BooleanField(default=False)),
                ('g_public_testing_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
